# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SwiftyTheme' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftyTheme
  pod 'SwiftyJSON'
  pod 'Moya'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'

  target 'SwiftyThemeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftyThemeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
